Remove override of use_blink_v8_binding_new_idl_interface.
The override was added in
https://github.com/brave/brave-core/pull/6195/commits/ea29650533277ae7bf629184fd63a9c01fb29352
due to build errors like

gen/third_party/blink/renderer/bindings/modules/v8/v8_shared_worker_global_scope.cc:4614:34: error: no member named 'isReportingObserversEnabled' in 'blink::ContextFeatureSettings'
       context_feature_settings->isReportingObserversEnabled())) {
       ~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.

As it turns out, the error were due to us making ReportingObservers
ContextEnabled in this change:
https://github.com/brave/brave-core/pull/4578/files

To fix added missing methods to blink::ContextFeatureSettings similarly
to how MojoJS is handled.